# Generated by Django 4.1.6 on 2023-02-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DepensesPerso', '0002_alter_user_usename_spendings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spendings',
            new_name='Spending',
        ),
    ]
