# Generated by Django 4.1.5 on 2023-02-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepensesPerso', '0003_rename_spendings_spending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='speAmount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
