# Generated by Django 4.1.5 on 2023-03-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepensesPerso', '0004_alter_spending_speamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spending',
            name='speBoughtBy',
        ),
        migrations.RemoveField(
            model_name='spending',
            name='speUsersInDebt',
        ),
        migrations.AddField(
            model_name='spending',
            name='speBoughtBy',
            field=models.CharField(default='aless', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spending',
            name='speUsersInDebt',
            field=models.ManyToManyField(to='DepensesPerso.user'),
        ),
    ]
