# Generated by Django 4.1.5 on 2023-03-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DepensesPerso', '0005_remove_spending_speboughtby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spending',
            name='speUsersInDebt',
        ),
        migrations.CreateModel(
            name='SpendingUserDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_owed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('spending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DepensesPerso.spending')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DepensesPerso.user')),
            ],
        ),
        migrations.AddField(
            model_name='spending',
            name='speUsersInDebtNew',
            field=models.ManyToManyField(through='DepensesPerso.SpendingUserDebt', to='DepensesPerso.user'),
        ),
    ]
