# Generated by Django 4.1.5 on 2023-03-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DepensesPerso', '0006_remove_spending_speusersindebt_spendinguserdebt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spendinguserdebt',
            name='amount_owed',
        ),
    ]
