# Generated by Django 4.1.5 on 2023-03-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepensesPerso', '0007_remove_spendinguserdebt_amount_owed'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendinguserdebt',
            name='amount_owed',
            field=models.DecimalField(decimal_places=2, default='null', max_digits=5),
            preserve_default=False,
        ),
    ]
