# Generated by Django 4.1.5 on 2023-03-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepensesPerso', '0008_spendinguserdebt_amount_owed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='useAmountOwed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='spendinguserdebt',
            name='amount_owed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
