# Generated by Django 4.1.5 on 2023-03-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepensesPerso', '0009_user_useamountowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='speBoughtBy',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
